version: '3.8'                  # Docker Compose file format version (leave as it is)

services:               
  clocks-frontend:   
    image: clocks-frontend                       
    build: 
      context: ./
      dockerfile: Dockerfile                  
    container_name: clocks-container 
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

